#r "nuget: Fun.Build, 1.1.15"

open System
open System.IO
open System.Xml.Linq
open Fun.Build

let nugetDir = __SOURCE_DIRECTORY__
let root = Path.GetFullPath(Path.Combine(nugetDir, ".."))
let srcDir = Path.Combine(root, "src")

// Projects to include in the Fable package, in compilation order
// Core must come first, then Worker.Context (base types), then others
let fableProjects = [
    // Core
    "Core/CloudFlare.Core", "Core/CloudFlare.Core"
    // Runtime (Worker.Context first as it has base types)
    "Runtime/CloudFlare.Worker.Context", "Runtime/CloudFlare.Worker.Context"
    "Runtime/CloudFlare.AI", "Runtime/CloudFlare.AI"
    "Runtime/CloudFlare.D1", "Runtime/CloudFlare.D1"
    "Runtime/CloudFlare.DurableObjects", "Runtime/CloudFlare.DurableObjects"
    "Runtime/CloudFlare.Hyperdrive", "Runtime/CloudFlare.Hyperdrive"
    "Runtime/CloudFlare.KV", "Runtime/CloudFlare.KV"
    "Runtime/CloudFlare.Queues", "Runtime/CloudFlare.Queues"
    "Runtime/CloudFlare.R2", "Runtime/CloudFlare.R2"
    "Runtime/CloudFlare.Vectorize", "Runtime/CloudFlare.Vectorize"
]

/// Extracts Compile Include items from an .fsproj file, preserving order
let getCompileItems (fsprojPath: string) : string list =
    let doc = XDocument.Load(fsprojPath)
    doc.Descendants(XName.Get("Compile", ""))
    |> Seq.append (doc.Descendants(XName.Get("Compile", "http://schemas.microsoft.com/developer/msbuild/2003")))
    |> Seq.choose (fun el ->
        el.Attribute(XName.Get("Include"))
        |> Option.ofObj
        |> Option.map (fun a -> a.Value))
    |> Seq.toList

/// Generates the unified CloudflareFS.fsproj for Fable
let generateFableFsproj () =
    printfn "Generating CloudflareFS.fsproj..."

    let compileItems =
        fableProjects
        |> List.collect (fun (projectPath, fablePath) ->
            let projectDir = Path.Combine(srcDir, projectPath)
            let fsprojFiles = Directory.GetFiles(projectDir, "*.fsproj")
            match fsprojFiles with
            | [| fsprojFile |] ->
                let files = getCompileItems fsprojFile
                let projectName = Path.GetFileName(projectPath)
                printfn "  %s: %d files" projectName (List.length files)
                files |> List.map (fun f -> sprintf "%s/%s" fablePath f)
            | [||] ->
                failwithf "No .fsproj found in %s" projectDir
            | _ ->
                failwithf "Multiple .fsproj files found in %s" projectDir
        )

    let compileItemsXml =
        compileItems
        |> List.map (fun path -> sprintf "    <Compile Include=\"%s\" />" path)
        |> String.concat "\n"

    let fsprojContent =
        String.concat "\n" [
            """<Project Sdk="Microsoft.NET.Sdk">"""
            """  <!--"""
            """    AUTO-GENERATED by build.fsx - DO NOT EDIT MANUALLY"""
            """"""
            """    This is a Fable-specific project file that consolidates all CloudflareFS"""
            """    source files into a single compilation unit for JavaScript generation."""
            """"""
            """    This file is NOT used for .NET compilation - each sub-project has its own .fsproj."""
            """    This exists purely for Fable to know how to compile the sources to JavaScript."""
            """"""
            """    To regenerate: cd nuget && dotnet fsi build.fsx"""
            """  -->"""
            """  <PropertyGroup>"""
            """    <TargetFramework>netstandard2.0</TargetFramework>"""
            """  </PropertyGroup>"""
            """"""
            """  <ItemGroup>"""
            compileItemsXml
            """  </ItemGroup>"""
            """"""
            """  <!-- NOTE: Management projects are NOT included for Fable compilation."""
            """       They use .NET-specific libraries (System.Net.Http, System.Text.Json)"""
            """       that have no Fable equivalents. Management projects are only available"""
            """       as .NET DLLs in lib/netstandard2.0/ -->"""
            """"""
            """  <ItemGroup>"""
            """    <PackageReference Include="Fable.Core" Version="4.3.0" />"""
            """    <PackageReference Include="Fable.Promise" Version="3.2.0" />"""
            """  </ItemGroup>"""
            """</Project>"""
            ""
        ]

    let outputPath = Path.Combine(nugetDir, "CloudflareFS.fsproj")
    File.WriteAllText(outputPath, fsprojContent)
    printfn "Generated: %s" outputPath

pipeline "Build and Pack" {
    description "Build and pack CloudflareFS NuGet package"

    stage "build" {
        workingDir root
        run "dotnet build CloudflareFS.sln -c Release"
    }

    stage "generate-fsproj" {
        run (fun _ ->
            generateFableFsproj ()
        )
    }

    stage "pack" {
        run "dotnet pack CloudflareFS.proj -c Release -o out"
    }

    runIfOnlySpecified false
}

tryPrintPipelineCommandHelp ()
